/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.selat.pipe;

import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.StreamsConfig;
import org.apache.kafka.streams.Topology;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Properties;
import java.util.concurrent.CountDownLatch;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class);
    public static void main(String[] args) {

        // Specify Streams execution configuration
        Properties props = new Properties();
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "streams-pipe");
        props.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass());
        props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass());

        // Create topology
        final StreamsBuilder builder = new StreamsBuilder();

        // Create stram from/to
        builder.stream("streams-plaintext-input").to("streams-pipe-output");

        // Create topology
        final Topology topology = builder.build();

        // Describe topology
        System.out.println(topology.describe());

        // Create Streams client
        final KafkaStreams streams = new KafkaStreams(topology, props);

        // Attach shutdown handler to catch control
        final CountDownLatch latch = new CountDownLatch(1);

        Runtime.getRuntime().addShutdownHook(new Thread("streams-shutdown-hook"){
            @Override
            public void run(){
                streams.close();
                latch.countDown();
            }
        });

        try {
            streams.start();
            latch.await();
        } catch (InterruptedException e) {
            logger.error("Error running stream", e);
        }
        System.exit(0);
    }
}
